version: "3.4"
volumes:
  data:
services:
  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=bossabox
  app:
    build: ./
    image: app
    links:
      - db
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASSWORD=123456
      - DB_DATABASE=bossabox
      - DB_PORT=3306
      - WAIT_HOSTS=db:3306

    ports:
      - 3000:3000
